spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery_management
    username: postgres
    password: hamza 786
    driverClassName: org.postgresql.Driver

application:
  security:
    jwt:
      secret-key: 2T82GOWAEO614T+VMIaybweXJWGA5mqDNlqHNVY/ZJw=
      expiration: 3600000

